# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1faKtrYc55WbDztw82eEpFhXe2UecTuLR
"""

# import module
import streamlit as st

# Title
st.title("Hello GeeksForGeeks !!!")